export const COMENZAR_DESCARGA_ACTIVIDADES = 'COMENZAR_DESCARGA_ACTIVIDADES';
export const DESCARGA_ACTIVIDADES_EXITO = 'DESCARGA_ACTIVIDADES_EXITO';
export const DESCARGA_ACTIVIDADES_ERROR = 'DESCARGA_ACTIVIDADES_ERROR';

export const AGREGAR_ACTIVIDAD = 'AGREGAR_ACTIVIDAD';
export const AGREGAR_ACTIVIDAD_EXITO = 'AGREGAR_ACTIVIDAD_EXITO';
export const AGREGAR_ACTIVIDAD_ERROR = 'AGREGAR_ACTIVIDAD_ERROR';

export const COMENZAR_DESCARGA_ACTIVIDADID = 'COMENZAR_DESCARGA_ACTIVIDADID';
export const DESCARGA_ACTIVIDADID_EXITO = 'DESCARGA_ACTIVIDADID_EXITO';
export const DESCARGA_ACTIVIDADID_ERROR = 'DESCARGA_ACTIVIDADID_ERROR';

export const OBTENER_ACTIVIDAD_EDITAR = 'OBTENER_ACTIVIDAD_EDITAR ';
export const COMENZAR_EDICION_ACTIVIDAD = 'COMENZAR_EDICION_ACTIVIDAD';
export const ACTIVIDAD_EDITADO_EXITO = 'ACTIVIDAD_EDITADO_EXITO ';
export const ACTIVIDAD_EDITADO_ERROR = 'ACTIVIDAD_EDITADO_ERROR';

export const OBTENER_ACTIVIDAD_ELIMINAR = 'OBTENER_ACTIVIDAD_ELIMINAR ';
export const ACTIVIDAD_ELIMINAR_EXITO = 'ACTIVIDAD_ELIMINAR_EXITO ';
export const ACTIVIDAD_ELIMINAR_ERROR = 'ACTIVIDAD_ELIMINAR_ERROR';

//________________________________NOVEDADES__________________________________

export const COMENZAR_DESCARGA_NEWS = 'COMENZAR_DESCARGA_NEWS';
export const DESCARGA_NEWS_EXITO = 'DESCARGA_NEWS_EXITO';
export const DESCARGA_NEWS_ERROR = 'DESCARGA_NEWS_ERROR';

export const CREAR_NEWS = 'NEWS_ACTIVIDAD';
export const CREAR_NEWS_EXITO = 'CREAR_NEWS_EXITO';
export const CREAR_NEWS_ERROR = 'CREAR_NEWS_ERROR';

export const OBTENER_NEWS_EDITAR = 'OBTENER_NEWS_EDITAR ';
export const COMENZAR_NEWS_ACTIVIDAD = 'COMENZAR_NEWS_ACTIVIDAD';
export const NEWS_EDITADO_EXITO = 'NEWS_EDITADO_EXITO ';
export const NEWS_EDITADO_ERROR = 'NEWS_EDITADO_ERROR';

export const OBTENER_NEWS_ELIMINAR = 'OBTENER_NEWS_ELIMINAR ';
export const NEWS_ELIMINAR_EXITO = 'NEWS_ELIMINAR_EXITO ';
export const NEWS_ELIMINAR_ERROR = 'NEWS_ELIMINAR_ERROR';

export const COMENZAR_OBTENER_NEWSID = 'COMENZAR_OBTENER_NEWSID';
export const OBTENER_NEWSID_EXITO = 'OBTENER_NEWSID_EXITO';
export const OBTENER_NEWSID_ERROR = 'OBTENER_NEWSID_ERROR';
