export const AGREGAR_NEWS = 'AGREGAR_NEWS';
export const AGREGAR_NEWS_EXITO = 'AGREGAR_NEWS_EXITO';
export const AGREGAR_NEWS_ERROR = 'AGREGAR_NEWS_ERROR';

export const COMENZAR_DESCARGAS_NEWS = 'COMENZAR_DESCARGAS_NEWS';
export const DESCARGAS_NEWS_EXITO = 'DESCARGAS_NEWS_EXITO'
export const DESCARGAS_NEWS_ERROR = 'DESCARGAS_NEWS_ERROR'